language: node_js
addons:
  firefox: latest
  chrome: stable
matrix:
  include:
    - os: linux
      node_js: "4"
    - os: linux
      env: CXX=g++-4.8
      node_js: "5"
    - os: linux
      node_js: "6"
    - os: linux
      env: CXX=g++-4.8
      node_js: "7"
    - os: osx
      node_js: "4"
    - os: osx
      node_js: "5"
    - os: osx
      node_js: "6"
    - os: osx
      node_js: "7"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
install:
  - npm install
script:
  - mkdir public
  - node --stack_size=100000 $(which npm) run build
  - npm run lint
  - npm run lint-styles
  - npm run test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
