version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: node:8
      - image: selenium/standalone-chrome:3.1.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: "Create artifacts directory"
          command: mkdir /tmp/artifacts
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: mkdir -p /tmp/artifacts/logs
      - run: DOCKER_HOST=localhost npm test
      - run: npm run build
      - run: npm test
      - store_artifacts:
          path: /tmp/artifacts
