name: deploy

on:
  push:
    branches: [ globe ]

jobs:
  deploy-pages:
    name: deploy/pages
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js from nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install
        run: npm ci

      - name: Build 
        run: npm run build

      - name: Upload to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
  
  # # publish docker to GitHub registry
  # deploy-docker:
  #   name: deploy/docker
  #   runs-on: ubuntu-latest

  #   if: ${{ github.event_name == 'push' }}

  #   strategy:
  #     fail-fast: false

  #   steps:
  #   - name: Login to GitHub Container Registry
  #     uses: docker/login-action@v3
  #     with:
  #       registry: ghcr.io
  #       username: ${{ github.actor }}
  #       password: ${{ secrets.GITHUB_TOKEN }}
  #   - uses: actions/checkout@v4
  #   - run: docker build -t ghcr.io/maplibre/maputnik:main .
  #   - run: docker push ghcr.io/maplibre/maputnik:main
